# The name of the label to apply when an issue does not have all tasks checked
labelName: check-to-do

# The color of the label in hex format (without #)
labelColor: ff4d4d

# The text of the comment to add to the issue in addition to the label
commentText: >
  Please don't forget to check all itens the isseu has.
  
# Whether or not to ensure all checkboxes are checked
checkCheckboxes: true

# Keywords to look for in the body of the issue
keywords:
  - gist
  - recreate
