 ##############################
  # example Advanced Settings
  ##############################
  mergeable:
    pull_requests:
      title:
        must_exclude:
          regex: 'wip'
          message: 'This PR is work in progress.'
        begins_with:
          match: '(feat)|(doc)|(fix)'
          message: 'Custom message...'
      label:
         must_exclude:
          regex: 'wip'
          message: 'Custom message. This PR is work in progress.'
